version: '3.7'
services:
#  mongodb:
#    image: mongo:5.0.3
#    container_name: mongodb_big_data
#    environment:
#      MONGO_INITDB_DATABASE: big_data
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: rootpassword
#    ports:
#      - 27017:27017
#    volumes:
#      - /home/big_data/mongodb_data_container:/data/db

#  mongo-express:
#    image: mongo-express
#    container_name: mongo_express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
#    image: elasticsearch:5.4
    container_name: es_big_data
    environment:
      discovery.type: single-node
#      - ES_JAVA_OPTS=-Xms6g -Xmx6g
#    volumes:
#      - /home/big_data/es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    network_mode: "elastic"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana_big_data
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://es_big_data:9200
    network_mode: "elastic"
    depends_on:
      - es

